---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server-tvl
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 16  # Optional but recommended
      SERVER_PASSWORD: "oreo123"  # Optional but recommended
      MULTITHREADING: "true"
      RCON_ENABLED: "true"
      RCON_PORT: "25575"
      TZ: "UTC"
      ADMIN_PASSWORD: "Antinem1"
      COMMUNITY: "True"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "Trizekiel_Helheim"
      SERVER_DESCRIPTION: "Hosted by Trizekiel - palworld docker by Thijs van Loef"
      DAY_TIME_SPEED_RATE: '0.8'
      NIGHT_TIME_SPEED_RATE: '1.5'
      EXP_RATE: '1.2'
      PAL_CAPTURE_RATE: '1.2'
      PAL_SPAWN_NUM_RATE: '1'
      PLAYER_STOMACH_DECREACE_RATE: '0.8'
      PLAYER_STAMINA_DECREACE_RATE: '0.9'
      PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP: '3'
      COLLECTION_DROP_RATE: '2.5'
      COLLECTION_OBJECT_RESPAWN_SPEED_RATE: '2'
      ENEMY_DROP_ITEM_RATE: '2'
      DEATH_PENALTY: 'Items'
      B_ENABLE_PLAYER_TO_PLAYER_DAMAGE: 'False'
      B_ENABLE_FRIENDLY_FIRE: 'False'
      B_ENABLE_INVADER_ENEMY: 'True'
      B_ACTIVE_UNKO: 'False'
      ENABLE_AIM_ASSIST_PAD: 'True'
      ENABLE_AIM_ASSIST_KEYBOARD: 'False'
      DROP_ITEM_MAX_NUM: '3000'
      DROP_ITEM_MAX_NUM_UNKO: '100'
      BASE_CAMP_MAX_NUM: '128'
      BASE_CAMP_WORKER_MAX_NUM: '20'
      DROP_ITEM_ALIVE_MAX_HOURS: '1'
      AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: 'False'
      AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: 'False'
      GUILD_PLAYER_MAX_NUM: '20'
      PAL_EGG_DEFAULT_HATCHING_TIME: '8'
      WORK_SPEED_RATE: '1.2'
      IS_MULTIPLAY: 'True'
      IS_PVP: 'True'
      CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: 'True'
      ENABLE_NON_LOGIN_PENALTY: 'False'
      ENABLE_FAST_TRAVEL: 'True'
      IS_START_LOCATION_SELECT_BY_MAP: 'True'
      EXIST_PLAYER_AFTER_LOGOUT: 'False'
      ENABLE_DEFENSE_OTHER_GUILD_PLAYER: 'False'
      COOP_PLAYER_MAX_NUM: '16'
      SERVER_PLAYER_MAX_NUM: '16'
      #PUBLIC_PORT: '8211'
      #PUBLIC_IP: '172.19.0.2'
      USE_AUTH: 'True'
    volumes:
      - ./palworld:/palworld/
