name: Palworld ACR Workflow

on: [push]

workflow_dispatch:
  inputs:
    tag:
      description: 'Palworld ACR tag'
      required: true
      default: 'latest'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker tag Palworld-linux-tvl-docker:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/Palworld-linux-tvl-docker:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/Palworld-linux-tvl-docker:latest